# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wharf < Formula
  desc "Terminal UI for managing Docker Compose stacks"
  homepage "https://github.com/idesyatov/wharf"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.2/wharf-v0.7.2-darwin-amd64.tar.gz"
      sha256 "0396d87bc4edd6fb5a16703801f94c58de8b7dffa0384b832fe1bf1cb27f231e"

      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.2/wharf-v0.7.2-darwin-arm64.tar.gz"
      sha256 "2d302c4ee667bc282933d8f7cf784431ca6cf7990030d877f501b6776438047d"

      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.2/wharf-v0.7.2-linux-amd64.tar.gz"
      sha256 "86dc24e36808d79df1faf251af61fe394c30618e7399003e6f97098a6542ae46"
      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.2/wharf-v0.7.2-linux-arm64.tar.gz"
      sha256 "303885884c69a8d9fe9e87711d13a57b7b534df68c8239ea63a7859058da6b33"
      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  test do
    system "#{bin}/wharf", "--version"
  end
end
