# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wharf < Formula
  desc "Terminal UI for managing Docker Compose stacks"
  homepage "https://github.com/idesyatov/wharf"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.3/wharf-v0.7.3-darwin-amd64.tar.gz"
      sha256 "ac1af90221b39c20c8053512c9f6c2c7c89940ff0ff56bac865cb12fdab154e5"

      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.3/wharf-v0.7.3-darwin-arm64.tar.gz"
      sha256 "462523a712b7d67b0b851aa9ff3ae4aa078c76fc325e9ad65a6dc5a5f88b033e"

      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.3/wharf-v0.7.3-linux-amd64.tar.gz"
      sha256 "a0417356fab55d366e8ad060af1aa9f942ef6224e6ec059458f8f9ca13d33668"
      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.7.3/wharf-v0.7.3-linux-arm64.tar.gz"
      sha256 "e4c59380631f28fad09cd2947ec90b9f8068d6657928a7d3369e18fa3f3d81af"
      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  test do
    system "#{bin}/wharf", "--version"
  end
end
