# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wharf < Formula
  desc "Terminal UI for managing Docker Compose stacks"
  homepage "https://github.com/idesyatov/wharf"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/idesyatov/wharf/releases/download/v0.5.1/wharf-v0.5.1-darwin-amd64.tar.gz"
      sha256 "02b6225a374b89d1390f481b1a636fc6ca617b2714984e39e5ac9c22e522665d"

      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/idesyatov/wharf/releases/download/v0.5.1/wharf-v0.5.1-darwin-arm64.tar.gz"
      sha256 "b4b8ff2ace506505aae5f76e1a006ca8cde4b23e7e42f767bc6eef5c4f9ff076"

      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.5.1/wharf-v0.5.1-linux-amd64.tar.gz"
      sha256 "0cd4cc270118b9a4545fb11f0a3019f4969801ef32c5035c5f409d9d19753557"
      define_method(:install) do
        bin.install "wharf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idesyatov/wharf/releases/download/v0.5.1/wharf-v0.5.1-linux-arm64.tar.gz"
      sha256 "b31ed1617829368e168521f6a1f51e101c871c513dd3aeef3f275ac45c7a1011"
      define_method(:install) do
        bin.install "wharf"
      end
    end
  end

  test do
    system "#{bin}/wharf", "--version"
  end
end
