# This file was generated by GoReleaser. DO NOT EDIT.
cask "wharf" do
  version "0.6.2"

  on_macos do
    on_intel do
      url "https://github.com/idesyatov/wharf/releases/download/v#{version}/wharf-v#{version}-darwin-amd64.tar.gz"
      sha256 "aa3f89ca7ab98157bad058b2e37f9c56040bffa5ad8721d244865cb65c2833a6"
    end
    on_arm do
      url "https://github.com/idesyatov/wharf/releases/download/v#{version}/wharf-v#{version}-darwin-arm64.tar.gz"
      sha256 "e1e313d46ecf73640240d2807c41e6bfbc377fa7b71342c344977541683e5db0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/idesyatov/wharf/releases/download/v#{version}/wharf-v#{version}-linux-amd64.tar.gz"
      sha256 "7c581000617a2c4be16a93e3472b92436e90607bed758f340f7a7046696a6f5f"
    end
    on_arm do
      url "https://github.com/idesyatov/wharf/releases/download/v#{version}/wharf-v#{version}-linux-arm64.tar.gz"
      sha256 "baca981154edd775cc616f3cc60f51f01faca4e9947db854272b6c6785c3967e"
    end
  end

  name "wharf"
  desc "Terminal UI for managing Docker Compose stacks"
  homepage "https://github.com/idesyatov/wharf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wharf"

  # No zap stanza required

end
